Feature 104
wisdomify/wisdomify pull request #106
Opened 2021-11-14 16:55 UTC by ArtemisDicoTiar

closes #104

2021-11-14 20:26 UTC, eubinecto requested changes

2021-11-14 20:26 UTC, eubinecto commented on wisdomify/apis.py
> +def get_wisdom():
이 함수는 어디에 쓰이는건가요? wisdoms를 접근하고 싶다면,
```python3
flow = ExperimentFlow()
flow.rd_flow.wisdoms
```
로 접근이 가능합니다. 이 함수가 굳이 필요없다면 제거해주세요!

2021-11-14 20:26 UTC, eubinecto commented on wisdomify/apis.py
> -    pass
검색을 위한 로직은 이미 flows.SearchFlow에 있는데요:
https://github.com/wisdomify/wisdomify/blob/c26f99ee68c6b7c3279826190ddee1e6f69686f1/wisdomify/flows.py#L54-L99

굳이 여기에 다시 중복해서 구현해놓은 이유가 있을까요?

2021-11-14 20:26 UTC, eubinecto commented on wisdomify/flows.py
> -        pass
이 부분은 지워도 괜찮을 것 같습니다!

2021-11-15 04:41 UTC, ArtemisDicoTiar commented on wisdomify/apis.py
> +def get_wisdom():
이전 구현에서 사용되었던 함수입니다 제거했습니다.

2021-11-15 04:43 UTC, ArtemisDicoTiar commented on wisdomify/apis.py
> -    pass
이전 구현에서 사용되었던 함수입니다 플로우로 대체했습니다.

2021-11-15 04:43 UTC, ArtemisDicoTiar commented on wisdomify/flows.py
> -        pass
지운게 표시된겁니다

2021-11-15 09:04 UTC, merged